"""changes to portuguese

Revision ID: 9cd2b0b69943
Revises: e5543882ab24
Create Date: 2025-08-04 08:15:36.078073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd2b0b69943'
down_revision: Union[str, None] = 'e5543882ab24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarios', sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('comentarios', 'created_at')
    op.add_column('usuarios', sa.Column('perfil', sa.String(), server_default='USUARIO', nullable=False))
    op.drop_column('usuarios', 'is_staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.drop_column('usuarios', 'perfil')
    op.add_column('comentarios', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('comentarios', 'data_criacao')
    # ### end Alembic commands ###
