"""lixos curtidos

Revision ID: c4b2549a7433
Revises: 9cd2b0b69943
Create Date: 2025-08-13 10:53:48.064683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b2549a7433'
down_revision: Union[str, None] = '9cd2b0b69943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensagens', sa.Column('curtidas', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensagens', 'curtidas')
    # ### end Alembic commands ###
