"""mudando campo role para is_staff

Revision ID: cf13c3dcde7a
Revises: 532945fad23f
Create Date: 2025-07-20 19:10:03.940299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf13c3dcde7a'
down_revision: Union[str, None] = '532945fad23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
