"""adds title field to message and changes role to is_staff

Revision ID: e5543882ab24
Revises: 532945fad23f
Create Date: 2025-07-30 12:02:23.801692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5543882ab24'
down_revision: Union[str, None] = '532945fad23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('title', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.drop_column('users', 'is_staff')
    op.drop_column('messages', 'title')
    # ### end Alembic commands ###
